//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautyStore.Models
{
    using System;
    using System.Collections.Generic;
    using BeautyStore.DesignPattern.Prototype;
    
    public partial class Brand : BrandClone
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Brand()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int BrandID { get; set; }
        public string BrandName { get; set; }
        public string BrandImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }

        //Mẫu Prototype
        public BrandClone Clone()
        {
            Brand newbrand = new Brand();
            newbrand.BrandName = BrandName;
            newbrand.BrandImage = BrandImage;
            return newbrand;
        }
    }
   

}
    
